### PR TITLE
Add option to ignore case when searching for the username property

### PR DESCRIPTION
**Pull request by erichelgeson**

### CODE REVIEW

**Comment by graemerocher** [comment]
This may not work for other implementations of GORM other than Hibernate. We would need to verify that.

**Comment by erichelgeson** [comment]
IgnoreCase does not work with mongo - `eq()` does not have the 3rd parameter in `MongoCriteriaBuilder`. I don't see a way to do this currently outside of hibernate correctly (I'm no mongodb expert though). If mongo has a way to do this we could potentially add that into GORM so it matches the interface `eq(prop, val, options)`

`ilike`/`=~` won't work because `%` is a valid character for an email address (so `%ric@eric.com` will match multiple, causing subtle issues.

Also as discussed on slack the other day `User.findWhere([email: "eric@eric.com"], [ignoreCase: true])` wont work since it ignores the second map in both hibernate and mongo (and probably suffers the same missing implementation)

IgnoreCase value is `false` by default it won't change anything for current users. I think having it simpler for a majority of users by not creating a custom UserDetailsService is a good thing. We could call out it only works for hibernate datastores. Also the GORM docs don't mention that ignoreCase only works with hibernate - http://docs.grails.org/3.2.0/ref/Domain%20Classes/createCriteria.html

I'll patch this PR to call the right constructor when ignoreCase is false.

**Comment by burtbeckwith** [comment]
Looks good, thanks for the PR.

**Comment by puneetbehl** [comment]
I believe we need to have something similar to following for MongoDB: 

```bash
db.book.find( { title: /^THE STAND$/i } );
```

**Pull request merged**
