### PR TITLE
Grails3 upgrade ... tests passed. ...... some work to be done (scripts)

### PR DESCRIPTION
**Pull request by Omasiri**

### CODE REVIEW

**Comment by codeconsole** [comment]
why are there failed checks?

**Comment by Omasiri** [comment]
@codeconsole: Maybe  the issue is coming from the travis config files.

**Comment by enr** [comment]
Trais build says:

    /home/travis/build.sh: line 175: ./gradlew: Permission denied

You need to `chmod +x` the `gradlew` file and commit it.

**Comment by Hi-Fi** [comment]
Replacing gradlew with one from new grails 3.0.1 application/plugin allowed build to continue locally.

**Comment by codeconsole** [comment]
@Omasiri looks like you need to resolve some merge conflicts :(

**Pull request closed without merging**
