### PR TITLE
Update README.md for Grails 6.0.x, 6.1.x and 6.2.x

### PR DESCRIPTION
**Pull request by jamesfredley**
Will release 6.1.2 after readme update + https://github.com/grails/grails-spring-security-core/pull/1037

### CODE REVIEW

**Review by matrei — APPROVED** [review]
Sorry, I've been out of the loop here - why is 6.1.x not compatible with Grails 6.0.x?

**Comment by jamesfredley** [comment]
I made that assumption based on the 6.1.x branch being built against [Grails 6.1.2](https://github.com/grails/grails-spring-security-core/blob/6.1.x/gradle/libs.versions.toml#L7), but looking further the 6.0.x branch is build against [Grails 6.1.0](https://github.com/grails/grails-spring-security-core/blob/6.0.x/gradle.properties#L2).  

Maybe 6.1.x and 6.0.x are compatible with Grails 6.0.x-6.2.x????

**Comment by jamesfredley** [comment]
5.1.x is built with [Grails 5.2.5](https://github.com/grails/grails-spring-security-core/blob/5.1.x/gradle.properties#L2) and 5.0.x is built with [Grails 5.1.1](https://github.com/grails/grails-spring-security-core/blob/5.0.x/gradle.properties#L2) so they are not staying with same versions.

**Comment by jamesfredley** [comment]
Closing as unneeded since grails-spring-security-core `6.0.x-6.1.x` are assumed compatible with Grails 6.0.x-6.2.x

**Pull request closed without merging**
