### PR TITLE
 upgraded to grails 3... todays rebase... All unit tests passed.

### PR DESCRIPTION
**Pull request by Omasiri**
Grails 3 upgrade. All unit tests passed but I did not upgrade the scripts.... The plugin descriptor may need some work. 
Separate branch recommended.

### CODE REVIEW

**Comment by graemerocher** [comment]
Ok thanks, will create a separate branch and merge this in via command line, it is a good start

**Comment by Omasiri** [comment]
Ok.

**Comment by graemerocher** [comment]
@Omasiri The `webxml` plugin won't work in Grails 3.0 as there is no web.xml file

**Comment by Omasiri** [comment]
Good to know... : ) 

Thanks.

**Comment by bdbogjoe** [comment]
good to know that this great plugin will have a grails 3 branch.
Is there any blocking issue ?

**Comment by bdbogjoe** [comment]
is it possible to create the grails3 branch ?
I'm interested to participate to grails3 migration

**Comment by burtbeckwith** [comment]
Will get on this soon, next week hopefully. Focusing on the 2.0 GA release first.

**Comment by Labi0** [comment]
I've opened a pull request for grails 3 acl plugin.

**Comment by burtbeckwith** [comment]
Thanks a ton for your help - this has saved me a lot of work and I'm looking forward to getting an M1 release of the plugin for Grails 3 out ASAP.

**Comment by bdbogjoe** [comment]
Good waiting for this release !

**Comment by codeconsole** [comment]
@burtbeckwith awesome, can't wait!  this has been my only blocker in upgrading to grails 3

**Comment by arvinlml** [comment]
Will there be an update on the documentation as well. Also will s2-quickstart be still available

**Comment by Schlogen** [comment]
@burtbeckwith Are you considering using spring security v4 in any future release?

**Pull request merged**
