### PR TITLE
Issue #554: Grails params missing values with PUT and PATCH after add spring security core

### PR DESCRIPTION
**Pull request by ddelponte**
Issue #554: Grails params missing values with PUT and PATCH after add spring security core

**Summary**

PUT requests with content-type `application/x-www-form-urlencoded` were not returning parameters when grails-spring-security-core was enabled.

The reason is that the `HttpPutFormContentFilter` was not registered.  Registering it allows for PUT requests to work as expected.

This PR does the following:

- adds `testCompile "org.grails:grails-datastore-rest-client:5.0.0.RC2"`to `build.gradle` so that I may have access to `RestBuilder` from within functional tests
- adds tests for `PUT` and `PATCH` requests that verify parameters are available for content-types of "application/x-www-form-urlencoded"
- adds a test controller for use during functional tests
- extends `HttpPutFormContentFilter` and overrides `doFilterInternal` so that it plays nicely with the request, i.e. not result in reading request body twice
- adds a new test config so that travis can verify params are in put requests
- adds secured endpoint to `TestFormParamsController` for use during testing
- modifies `travis-build.sh` to kick off form param tests

### CODE REVIEW

**Comment by sdelamo** [comment]
@ddelponte could add a test for this line:
https://github.com/grails-plugins/grails-spring-security-core/blob/issue554/plugin/src/main/groovy/grails/plugin/springsecurity/web/filter/GrailsHttpPutFormContentFilter.groovy#L41

**Comment by ddelponte** [comment]
@sdelamo it looks like your changes have broken some `StaticSecuritySpec` tests.  
Would you be able to take a look.

I've spent some time debugging and it's not obvious to me why your changes would cause the internal server error we're now seeing.

I've confirmed that rolling back the code prior to your commits allows the tests to pass.

**Comment by ddelponte** [comment]
I resolved the last of the failing tests by reverting a change I inadvertently committed to `application.groovy`: 80563ff9766b60f7acd7e5dae10ccf8a7418829c

I've also verified that the line of code you referenced for a test:  https://github.com/grails-plugins/grails-spring-security-core/blob/issue554/plugin/src/main/groovy/grails/plugin/springsecurity/web/filter/GrailsHttpPutFormContentFilter.groovy#L41

is tested in both `RoleSpec` and `TestFormParamsControllerSpec`.

I think this may be ready to merge

**Comment by sdelamo** [comment]
Thanks @ddelponte
I have created a commit with Squashed commits of this PR.

**Pull request closed without merging**
