### PR TITLE
Build with Grails 2.5, Spring Security Core 3.2.8

### PR DESCRIPTION
**Pull request by tcrossland**

### CODE REVIEW

**Comment by burtbeckwith** [comment]
Master is Grails 3, use the 2.x branch for the Grails 2 plugin. Closing since there's rarely any benefit to using a newer version of Grails for developing plugins, only for apps. It's trivial to update to the latest version of Spring Security, will do that for the next release.

**Comment by tcrossland** [comment]
The PR also contains this commit (https://github.com/tcrossland/grails-spring-security-core/commit/d66d44bfc80ebe956b99bdde95d7b358f358fb18) which ensures the test apps (and Travis build) test the current version of the plugin instead of any old 2.0-SNAPSHOT version that happens to be installed.

**Comment by tcrossland** [comment]
@burtbeckwith would you like me to create a new PR for the grails 2 branch with the fix for the test apps? Or should I create an issue. (This PR was created in July before any grails 3 work had been done on the plugin).

**Comment by tcrossland** [comment]
See #388

**Pull request closed without merging**
