### PR TITLE
Change default SecurityContextHolderStrategy to MODE_INHERITABLETHREADLOCAL to make using the plugin in new threads easier

### PR DESCRIPTION
**Pull request by ddelponte**
This PR is inspired by [PR 375](https://github.com/grails-plugins/grails-spring-security-core/pull/375).  [PR 375](https://github.com/grails-plugins/grails-spring-security-core/pull/375) was created back on Sep 6, 2015 but conflicts have arisen since its creation.

I spoke with the PR's creator, @jameskleeh , and he was okay with the idea of me creating a new PR with his changes that resolves the conflicts.

That's what this PR is!

The goal of this PR is to

> Change default SecurityContextHolderStrategy to MODE_INHERITABLETHREADLOCAL to make using the plugin in new threads easier

### CODE REVIEW

**Comment by ddelponte** [comment]
retest this please

**Comment by ddelponte** [comment]
The changes introduced in the [original PR ](https://github.com/grails-plugins/grails-spring-security-core/pull/375)are causing tests to fail.  This will require further investigation.

image
image
image
image

Tagging @jameskleeh because you may also be interested in the results ☝️

**Comment by sdelamo** [comment]
The tests which fail: 

https://github.com/grails-plugins/grails-spring-security-core/blob/master/integration-test-app/src/integration-test/groovy/grails/plugin/springsecurity/SpringSecurityUtilsIntegrationSpec.groovy#L159

https://github.com/grails-plugins/grails-spring-security-core/blob/master/integration-test-app/src/integration-test/groovy/grails/plugin/springsecurity/SpringSecurityUtilsIntegrationSpec.groovy#L185

https://github.com/grails-plugins/grails-spring-security-core/blob/master/integration-test-app/src/integration-test/groovy/grails/plugin/springsecurity/SpringSecurityUtilsIntegrationSpec.groovy#L205

Do actually test that SecurityContextHolder strategoy name is `SecurityContextHolder.MODE_THREADLOCAL`.

I see two options:

- we keep the strategoryName `SecurityContextHolder.MODE_THREADLOCAL`
- we change the default stategoryName to `SecurityContextHolder.MODE_INHERITABLETHREADLOCAL`. But we will need to update the tests to verify the behaviour is the expected with `MODE_INHERITABLETHREADLOCAL` and we should document this default configuration change as well.

**Comment by ddelponte** [comment]
This PR got borked after performing a rebase.  I've been unable to resolve so I've decided to close this PR and open up a new PR at https://github.com/grails-plugins/grails-spring-security-core/pull/517

**Pull request closed without merging**
