### PR TITLE
Issue 566: isFullyAuthenticated() leads to redirect-loop in Grails 3.3.x

### PR DESCRIPTION
**Pull request by ddelponte**
The issue appears to be related to the order in which the RememberMe filter was being loaded.

 This was resulting in a redirect loop caused by the `AccessDeniedException` being repeatedly thrown and then handled by the `ExceptionTranslationFilter`.

 The `AccessDeniedException` was being thrown because it was always checking the original requested URL, in this case `/role/index`.

 The request to `/role/index` is expected to throw an `AccessDeniedException` because that url is marked as requiring full authentication.  Auto logging in with a RememberMe token is not considered to be fully authenticated.

 The problem was, it kept rechecking that original requested URL and never properly redirected to /login/auth.

 Reordering of the filters allows the filter chain to proceed as expected.

### CODE REVIEW

**Comment by ddelponte** [comment]
This is a fix for Issue #566

**Comment by ddelponte** [comment]
FYI - tests are failing but it is because of previous changes which implement Micronaut client support.

**Comment by bassmartin** [comment]
Any traction on this issue?

**Comment by ddelponte** [comment]
@bassmartin I'm working on fixing the failing tests atm.

**Comment by ddelponte** [comment]
Tests are now passing on Travis CI!  ✨

**Comment by robertoschwald** [comment]
Any timeframe when this will be merged and a new 3.3.x version released?

**Comment by ddelponte** [comment]
@sdelamo, are you able to provide @robertoschwald with a timeframe?

**Pull request merged**
