### PR TITLE
Ajax login fix. https://jira.grails.org/browse/GPSPRINGSECURITYCORE-320

### PR DESCRIPTION
**Pull request by codeconsole**
Upon a successful ajax login, if there is a html page in the request cache from a previous unauthorized html page, the html for that page will be sent back instead of the ajax response. Also, there is no need to access the super methods when request is ajax.

Another words: if you view a page that requires access, then log in with ajax.  Instead of getting a json response, you get the html and your ajax code crashes.  This fixes that.

https://jira.grails.org/browse/GPSPRINGSECURITYCORE-320

### CODE REVIEW

**Comment by codeconsole** [comment]
Any way to force Travis to re-run the tests?

**Comment by codeconsole** [comment]
https://jira.grails.org/browse/GPSPRINGSECURITYCORE-320

**Comment by graemerocher** [comment]
Why were tests deleted as part of the pull request?

**Comment by codeconsole** [comment]
The tests tested a method that I deleted -> determineTargetUrl.  It is overly redundant and not needed.

determineTargetUrl checks to see if a request is ajax, if it is, it returns the ajax url, otherwise it calls super.

The bug is caused in onAuthenticationSuccess.  Before it was calling super, which internally checks the request cache first, so if you have a request in the request cache, it will not call this methods determineTargetUrl.  Therefore you do not want to call super if the request is ajax, because it will never invoke determineTargetUrl.

The alternative would have been to keep the method as is and call it from onAuthenticationSuccess, but if the request is not ajax, you would be essentially checking to see if a request is ajax twice, which is overly redundant.

**Comment by codeconsole** [comment]
hi @graemerocher 
I added the tests back.  I just changed the method they test on.

**Pull request merged**
