### PR TITLE
upgraded to grails 3

### PR DESCRIPTION
**Pull request by Omasiri**
Grails 3 branch for spring security core.

### CODE REVIEW

**Comment by burtbeckwith** [comment]
I can't consider a pull request that deletes _every_ test

**Comment by Omasiri** [comment]
Hello @burtbeckwith,
The tests are not deleted :)  integration and functional tests can be found under scr/integration and src/functional respectively. Unit tests can be found under src/tests. 
Those are the new locations for test files in grails 3. The structure is different from grails 2.* so I recommend you create a separate branch for this pull request.

**Comment by burtbeckwith** [comment]
Sorry, that wasn't clear from looking at the GitHub diff. Do the tests pass?

**Comment by Omasiri** [comment]
currently 75% successful :(

**Pull request closed without merging**
